name: build and tests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
    workflow_dispatch: {}


env:
    CI: true

jobs:
    tests:
        name: Build and test validation
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v2

            # Use specific Node.js version
            - name: Use Node.js 15.x
              uses: actions/setup-node@v2
              with:
                  node-version: 15.x

            # Install packages
            - name: Install packages
              run: npm ci

            # Prepare before build
            - name: Prepare
              run: npm run prepare

            # Check linter
            - name: Linter
              run: npm run lint -- --max-warnings=0

            # Build bundle
            - name: Build bundle
              if: ${{ success() }}
              run: npm run build

            # Run unit tests
            - name: Unit tests
              run: npm run test-with-coverage_lcov

            # Run functional tests
            - name: Functional tests
              if: ${{ success() }}
              run: npm run test-functional

            # Code coverage
            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}

            # Build documentation
            - name: Build documentation
              if: ${{ success() && github.ref == 'refs/heads/master' }}
              if: ${{ success() }}
              run: npm run doc -- -d buildDocs

            # Prepare archive for deploying
            - name: Archive production artifacts
              if: ${{ success() && github.ref == 'refs/heads/master' }}
              uses: actions/upload-artifact@v2
              with:
                  name: dist-itowns
                  path: |
                      dist/**/*.js
                      examples
                      buildDocs
